[2024-10-30T04:52:49.825+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-30T04:52:50.311+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_excel_to_postgres.load_excel_task manual__2024-10-30T04:52:44.612766+00:00 [queued]>
[2024-10-30T04:52:50.345+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_excel_to_postgres.load_excel_task manual__2024-10-30T04:52:44.612766+00:00 [queued]>
[2024-10-30T04:52:50.346+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-30T04:52:50.388+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): load_excel_task> on 2024-10-30 04:52:44.612766+00:00
[2024-10-30T04:52:50.404+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=76) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-30T04:52:50.407+0000] {standard_task_runner.py:72} INFO - Started process 78 to run task
[2024-10-30T04:52:50.406+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'load_excel_to_postgres', 'load_excel_task', 'manual__2024-10-30T04:52:44.612766+00:00', '--job-id', '294', '--raw', '--subdir', 'DAGS_FOLDER/excel_to_pg.py', '--cfg-path', '/tmp/tmpy0l1rvgs']
[2024-10-30T04:52:50.416+0000] {standard_task_runner.py:105} INFO - Job 294: Subtask load_excel_task
[2024-10-30T04:52:50.509+0000] {task_command.py:467} INFO - Running <TaskInstance: load_excel_to_postgres.load_excel_task manual__2024-10-30T04:52:44.612766+00:00 [running]> on host 6b6b0d1c2d7e
[2024-10-30T04:52:50.757+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_excel_to_postgres' AIRFLOW_CTX_TASK_ID='load_excel_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-30T04:52:44.612766+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-30T04:52:44.612766+00:00'
[2024-10-30T04:52:50.765+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-30T04:52:50.869+0000] {base.py:84} INFO - Retrieving connection 'postgre_conn'
[2024-10-30T04:52:54.440+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-30T04:52:54.487+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-30T04:52:54.490+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=load_excel_to_postgres, task_id=load_excel_task, run_id=manual__2024-10-30T04:52:44.612766+00:00, execution_date=20241030T045244, start_date=20241030T045250, end_date=20241030T045254
[2024-10-30T04:52:54.575+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-30T04:52:54.613+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-30T04:52:54.632+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
