[2024-10-28T05:28:39.834+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-28T05:28:39.914+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_to_snowflake_etl.extract_task manual__2024-10-28T05:27:58.044590+00:00 [queued]>
[2024-10-28T05:28:39.965+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_to_snowflake_etl.extract_task manual__2024-10-28T05:27:58.044590+00:00 [queued]>
[2024-10-28T05:28:39.988+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-28T05:28:40.171+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): extract_task> on 2024-10-28 05:27:58.044590+00:00
[2024-10-28T05:28:40.555+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=179) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-28T05:28:40.559+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'postgres_to_snowflake_etl', 'extract_task', 'manual__2024-10-28T05:27:58.044590+00:00', '--job-id', '82', '--raw', '--subdir', 'DAGS_FOLDER/pg_sf.py', '--cfg-path', '/tmp/tmp4ugvt76q']
[2024-10-28T05:28:40.576+0000] {standard_task_runner.py:72} INFO - Started process 181 to run task
[2024-10-28T05:28:40.577+0000] {standard_task_runner.py:105} INFO - Job 82: Subtask extract_task
[2024-10-28T05:28:40.840+0000] {task_command.py:467} INFO - Running <TaskInstance: postgres_to_snowflake_etl.extract_task manual__2024-10-28T05:27:58.044590+00:00 [running]> on host d944eca59341
[2024-10-28T05:28:43.141+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_to_snowflake_etl' AIRFLOW_CTX_TASK_ID='extract_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-28T05:27:58.044590+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-28T05:27:58.044590+00:00'
[2024-10-28T05:28:43.239+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-28T05:28:44.068+0000] {base.py:84} INFO - Retrieving connection 'postgre_conn'
[2024-10-28T05:28:49.581+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-28T05:28:49.606+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-28T05:28:49.607+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=postgres_to_snowflake_etl, task_id=extract_task, run_id=manual__2024-10-28T05:27:58.044590+00:00, execution_date=20241028T052758, start_date=20241028T052839, end_date=20241028T052849
[2024-10-28T05:28:49.698+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-28T05:28:49.750+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-28T05:28:49.764+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
