[2024-10-29T03:31:09.955+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-29T03:31:10.003+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_to_mysql_etl.extract_task manual__2024-10-29T03:30:57.215092+00:00 [queued]>
[2024-10-29T03:31:10.021+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_to_mysql_etl.extract_task manual__2024-10-29T03:30:57.215092+00:00 [queued]>
[2024-10-29T03:31:10.023+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-29T03:31:10.068+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): extract_task> on 2024-10-29 03:30:57.215092+00:00
[2024-10-29T03:31:10.075+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=123) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-29T03:31:10.077+0000] {standard_task_runner.py:72} INFO - Started process 124 to run task
[2024-10-29T03:31:10.079+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'postgres_to_mysql_etl', 'extract_task', 'manual__2024-10-29T03:30:57.215092+00:00', '--job-id', '116', '--raw', '--subdir', 'DAGS_FOLDER/pg_my.py', '--cfg-path', '/tmp/tmp12vd8cm5']
[2024-10-29T03:31:10.081+0000] {standard_task_runner.py:105} INFO - Job 116: Subtask extract_task
[2024-10-29T03:31:10.186+0000] {task_command.py:467} INFO - Running <TaskInstance: postgres_to_mysql_etl.extract_task manual__2024-10-29T03:30:57.215092+00:00 [running]> on host fe15dc428079
[2024-10-29T03:31:10.374+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_to_mysql_etl' AIRFLOW_CTX_TASK_ID='extract_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-29T03:30:57.215092+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-29T03:30:57.215092+00:00'
[2024-10-29T03:31:10.375+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-29T03:31:10.479+0000] {base.py:84} INFO - Retrieving connection 'postgre_conn'
[2024-10-29T03:31:10.981+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-29T03:31:11.008+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-29T03:31:11.009+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=postgres_to_mysql_etl, task_id=extract_task, run_id=manual__2024-10-29T03:30:57.215092+00:00, execution_date=20241029T033057, start_date=20241029T033110, end_date=20241029T033111
[2024-10-29T03:31:11.098+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-29T03:31:11.259+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
