[2024-10-29T03:32:35.674+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-29T03:32:35.700+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_to_mysql_etl.load_task manual__2024-10-29T03:32:26.471869+00:00 [queued]>
[2024-10-29T03:32:35.712+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_to_mysql_etl.load_task manual__2024-10-29T03:32:26.471869+00:00 [queued]>
[2024-10-29T03:32:35.715+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-29T03:32:35.761+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): load_task> on 2024-10-29 03:32:26.471869+00:00
[2024-10-29T03:32:35.780+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=146) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-29T03:32:35.785+0000] {standard_task_runner.py:72} INFO - Started process 147 to run task
[2024-10-29T03:32:35.786+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'postgres_to_mysql_etl', 'load_task', 'manual__2024-10-29T03:32:26.471869+00:00', '--job-id', '119', '--raw', '--subdir', 'DAGS_FOLDER/pg_my.py', '--cfg-path', '/tmp/tmpwqebffv3']
[2024-10-29T03:32:35.792+0000] {standard_task_runner.py:105} INFO - Job 119: Subtask load_task
[2024-10-29T03:32:35.906+0000] {task_command.py:467} INFO - Running <TaskInstance: postgres_to_mysql_etl.load_task manual__2024-10-29T03:32:26.471869+00:00 [running]> on host fe15dc428079
[2024-10-29T03:32:36.072+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_to_mysql_etl' AIRFLOW_CTX_TASK_ID='load_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-29T03:32:26.471869+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-29T03:32:26.471869+00:00'
[2024-10-29T03:32:36.074+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-29T03:32:36.129+0000] {base.py:84} INFO - Retrieving connection 'mysql_conn'
[2024-10-29T03:32:42.999+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-29T03:32:43.019+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-29T03:32:43.020+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=postgres_to_mysql_etl, task_id=load_task, run_id=manual__2024-10-29T03:32:26.471869+00:00, execution_date=20241029T033226, start_date=20241029T033235, end_date=20241029T033243
[2024-10-29T03:32:43.113+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-29T03:32:43.141+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-29T03:32:43.152+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
