[2024-10-30T04:51:25.867+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-30T04:51:25.906+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_excel_to_postgres.load_excel_task manual__2024-10-30T04:43:02.386596+00:00 [queued]>
[2024-10-30T04:51:25.934+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_excel_to_postgres.load_excel_task manual__2024-10-30T04:43:02.386596+00:00 [queued]>
[2024-10-30T04:51:25.936+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 1
[2024-10-30T04:51:25.967+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): load_excel_task> on 2024-10-30 04:43:02.386596+00:00
[2024-10-30T04:51:25.977+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=51) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-30T04:51:25.980+0000] {standard_task_runner.py:72} INFO - Started process 60 to run task
[2024-10-30T04:51:25.989+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'load_excel_to_postgres', 'load_excel_task', 'manual__2024-10-30T04:43:02.386596+00:00', '--job-id', '293', '--raw', '--subdir', 'DAGS_FOLDER/excel_to_pg.py', '--cfg-path', '/tmp/tmpgcjzgewk']
[2024-10-30T04:51:25.993+0000] {standard_task_runner.py:105} INFO - Job 293: Subtask load_excel_task
[2024-10-30T04:51:26.092+0000] {task_command.py:467} INFO - Running <TaskInstance: load_excel_to_postgres.load_excel_task manual__2024-10-30T04:43:02.386596+00:00 [running]> on host 6b6b0d1c2d7e
[2024-10-30T04:51:26.699+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_excel_to_postgres' AIRFLOW_CTX_TASK_ID='load_excel_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-30T04:43:02.386596+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-30T04:43:02.386596+00:00'
[2024-10-30T04:51:26.702+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-30T04:51:26.861+0000] {base.py:84} INFO - Retrieving connection 'postgre_conn'
[2024-10-30T04:51:30.056+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-30T04:51:30.147+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-30T04:51:30.156+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=load_excel_to_postgres, task_id=load_excel_task, run_id=manual__2024-10-30T04:43:02.386596+00:00, execution_date=20241030T044302, start_date=20241030T045125, end_date=20241030T045130
[2024-10-30T04:51:30.334+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-30T04:51:30.367+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-30T04:51:30.381+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
